<Project>
  <Import Project="Versions.props" Condition="'$(WindowsAppSDKVersion)' == ''" />

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="$(WindowsAppSDKVersion)" />
  </ItemGroup>
</Project>
