<Project>
  <PropertyGroup>
    <ExperimentalApisAvailable Condition="$([System.String]::Copy('$(WindowsAppSDKVersion)').Contains('-exp'))">true</ExperimentalApisAvailable>
    <ExperimentalApisAvailable Condition="'$(BuildExperimentalExtensions)' == 'true'">true</ExperimentalApisAvailable>
    <ExperimentalApisAvailable Condition="'$(ExperimentalApisAvailable)' == ''">false</ExperimentalApisAvailable>
  </PropertyGroup>

  <ItemGroup>
    <!-- StableExtension entries are always referenced. -->

    <ExperimentalExtension Include="HelloUserControl" />
    <ExperimentalExtension Include="HelloPage" />
  </ItemGroup>
</Project>
